### ISSUE TITLE
Lookup fails with MySQLSyntaxErrorException about Function `any_value`

### ISSUE THREAD

**Issue by tobyp** [ezeiger92/Prism-Bukkit#10] opened 2018-10-21 16:54 UTC
Lookups fail with an SQL error, with the inspection wand as well as the lookup command.
This was introduced with the latest commit 44eb961d3 (I built & tested previous commit; works fine).

I don't know exactly what the `any_value` wrappers are supposed to achieve, so I'm not sure how to fix this.

OS: Arch Linux
Minecraft Server: CraftBukkit version git-Spigot-f6a273b-8ab46ff (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
SQL Server: mariadb 10.1.36-1
ezeiger92/Prism-Bukkit: 44eb961d3

```[INFO]: tobyp issued server command: /pr l r:20 t:2w
[INFO]: [Prism]: Database connection error: FUNCTION prism.any_value does not exist
[WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: FUNCTION prism.any_value does not exist
[WARN]:         at sun.reflect.GeneratedConstructorAccessor79.newInstance(Unknown Source)
[WARN]:         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[WARN]:         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[WARN]:         at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[WARN]:         at com.mysql.jdbc.Util.getInstance(Util.java:408)
[WARN]:         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[WARN]:         at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
[WARN]:         at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
[WARN]:         at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[WARN]:         at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[WARN]:         at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
[WARN]:         at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[WARN]:         at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
[WARN]:         at me.botsko.prism.actionlibs.ActionsQuery.lookup(ActionsQuery.java:125)
[WARN]:         at me.botsko.prism.commands.LookupCommand$1.run(LookupCommand.java:69)
[WARN]:         at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76)
[WARN]:         at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[WARN]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[WARN]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[WARN]:         at java.lang.Thread.run(Thread.java:748)
```

**Comment by Narimm** [comment] 2019-05-30 01:12
I am working on a database abstraction for this - the issue is that ANY_VALUE is not supported by MariaDB but they are on Oracle MYSQL.  To support this break from SQL standard we need to either change the function to MIN() or create a number of datasources and support them

https://github.com/AddstarMC/Prism-Bukkit/tree/Database-Abstraction is the branch that contains the abstraction but I am still getting it tested

**Comment by TNTUP** [comment] 2019-05-30 09:43
@Narimm If your fork works nicely with 1.13.x and 1.14.x im switching to it right away! Seeing it still in testing phase ill just wait until it comes stable and if its fine with 1.12.2 aswell. For now for 1.13.x servers im using Core Protect, its nice, but I'm so used with Prism since I created the server in Jul 2013

**Comment by Narimm** [comment] 2019-05-31 00:00
I just merged that fork into master I tested it on 1.14.2 last night and it works as expected

**Comment by Narimm** [comment] 2019-05-31 00:00
You can find it on the build server 
https://jenkins.addstar.com.au

**Comment by Narimm** [comment] 2019-05-31 00:05
Make sure if your using MariaDb you set 
`useNonStandardSql = false`

**Comment by TNTUP** [comment] 2019-06-01 07:22
Can't seem to download them and they're made for 1.14, Creative server is on 1.13.2, 1.14.x isn't production ready yet :(

**Closed as completed** 2021-04-07 10:14 UTC
